name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.7.0
  - annotated-types=0.6.0
  - archspec=0.2.3
  - asttokens=3.0.0
  - boltons=24.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.9.9
  - certifi=2025.10.5
  - cffi=1.17.1
  - uvicorn
  - charset-normalizer=3.3.2
  - comm=0.2.3
  - conda=25.7.0
  - conda-anaconda-telemetry=0.1.2
  - conda-anaconda-tos=0.1.3
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=44.0.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - distro=1.9.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fmt=9.1.0
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libarchive=3.7.7
  - libcurl=8.12.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - menuinst=2.2.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.2
  - openssl=3.0.18
  - packaging=24.2
  - parso=0.8.5
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pyzmq=26.2.0
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rich=13.9.4
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - setuptools=78.1.1
  - simdjson=3.10.1
  - six=1.17.0
  - spdlog=1.11.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - anyio==4.11.0
      - applicationinsights==0.11.10
      - argparse==1.4.0
      - attrs==25.3.0
      - backports-csv==1.0.7
      - beautifulsoup4==4.13.5
      - boto3==1.40.36
      - botocore==1.40.36
      - cachetools==5.5.2
      - cli-helpers==0.2.3
      - click==7.0
      - configobj==5.0.9
      - contourpy==1.3.2
      - cycler==0.12.1
      - defusedxml==0.7.1
      - distlib==0.4.0
      - enum34==1.1.10
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - fonttools==4.58.2
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - future==1.0.0
      - google==3.0.0
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-cloud-core==2.4.3
      - google-cloud-translate==3.21.1
      - googleapis-common-protos==1.70.0
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.75.0
      - grpcio-status==1.75.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanize==4.14.0
      - jinja2==3.1.6
      - jiter==0.11.0
      - jmespath==1.0.1
      - joblib==1.5.2
      - kiwisolver==1.4.8
      - lxml==6.0.2
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - mssql-cli==1.0.0
      - multidict==6.6.4
      - networkx==3.5
      - numpy==2.3.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openai==0.28.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.3.0
      - pandas-read-xml==0.3.1
      - pillow==11.2.1
      - prompt-toolkit==2.0.10
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==6.32.1
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.3
      - pyside6==6.9.2
      - pyside6-addons==6.9.2
      - pyside6-essentials==6.9.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - rsa==4.9.1
      - s3transfer==0.14.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shiboken6==6.9.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlparse==0.2.4
      - supervision==0.25.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - torch==2.7.1
      - torchvision==0.22.1
      - triton==3.3.1
      - tzdata==2025.2
      - ultralytics==8.3.153
      - ultralytics-thop==2.0.14
      - xmltodict==1.0.2
      - yarl==1.20.1
      - zipfile36==0.1.3
